external-fsl-toolchain: Add NATIVEDEPS to DEPENDS
When the external toolchain is used, the toolchain inside Yocto doesn't get
built. Ergo, the native versions of GMP, MPFR and MPC aren't built.

This is a problem, since the compiler needs all of them. If they aren't built,
g++ picks up system headers and throws a lot of errors, such as:

/home/para/Desktop/sdk-v1.6.x/build_p5020ds-64b_release/tmp/work-shared/gcc-4.8.1+fsl-r0/gcc-4.8.1+fsl/gcc/system.h:444:23: error: declaration of C function 'void* sbrk(int)' conflicts with/usr/include/unistd.h:1067:14
/usr/include/unistd.h:1067:14: error: previous declaration 'void* sbrk(intptr_t)' here

/home/para/Desktop/sdk-v1.6.x/build_p5020ds-64b_release/tmp/work-shared/gcc-4.8.1+fsl-r0/gcc-4.8.1+fsl/gcc/system.h:448:48: error: new declaration 'char* strstr(const char*, const char*)'
/usr/include/string.h:335:1: error: ambiguates old declaration 'const char* strstr(const char*, const char*)'

Signed-off-by: Cosmin Paraschiv <cosmin.paraschiv@freescale.com>
Change-Id: Iddfeae176e33ca6d0cb130a617f5167f84650b9d
Reviewed-on: http://git.am.freescale.net:8181/12462
Reviewed-by: Alexandru Cezar Sardan <alexandru.sardan@freescale.com>
Reviewed-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Tested-by: Zhenhua Luo <zhenhua.luo@freescale.com>