Revert "Revert "gcc: included patch to use $base_libdir for the multilib directory layout""
This reverts commit 95156c2583a2777b9cf03906521fa5c65f79693c.

The real fix for kernel build issue is fixed, resume the commit.
    error: libgcc.a is missing