gcc: Specify which branch to use.
BitBake's Git fetcher has been given branch awareness. If a branch
is not explicitly given, it uses the default one, master.

Since our revision isn't on the master branch, the following error
is thrown:

WARNING: Failed to fetch URL git://git.am.freescale.net/gitolite/sdk/gcc.git;destsuffix=gcc-4.8.1+fsl, attempting MIRRORS if available
ERROR: Fetcher failure: Unable to find revision d08552bd37bddd6b0eac05e5e8e8cc0cfc2a9bbe in branch master even from upstream
ERROR: Function failed: Fetcher failure for URL: 'git://git.am.freescale.net/gitolite/sdk/gcc.git;destsuffix=gcc-4.8.1+fsl'. Unable to fetch URL from any source.

Signed-off-by: Cosmin Paraschiv <cosmin.paraschiv@freescale.com>
Change-Id: Id82a640a955ff8aaf8f934d7886146a1994ae7ac
Reviewed-on: http://git.am.freescale.net:8181/7965
Reviewed-by: Catalin-Dan Udma <catalin.udma@freescale.com>
Reviewed-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Tested-by: Zhenhua Luo <zhenhua.luo@freescale.com>