gcc: unify source for all gcc variants
When different gcc source is used for different gcc variants, following build
error might appear occasionally.
ERROR: The stack trace of python calls that resulted in this exception/failure was:
ERROR:   File "base_do_unpack", line 19, in <module>
ERROR:
ERROR:   File "base_do_unpack", line 14, in base_do_unpack
ERROR:
ERROR:   File "/local/cache-build-32bit/poky/bitbake/lib/bb/fetch2/__init__.py", line 1466, in unpack
ERROR:     ud.method.unpack(ud, root, self.d)
ERROR:
ERROR:   File "/local/cache-build-32bit/poky/bitbake/lib/bb/fetch2/git.py", line 239, in unpack
ERROR:     bb.utils.prunedir(destdir)
ERROR:
ERROR:   File "/local/cache-build-32bit/poky/bitbake/lib/bb/utils.py", line 561, in prunedir
ERROR:     os.rmdir(os.path.join(root, name))
ERROR:
ERROR: The code that was being executed was:
ERROR:      0015:    except bb.fetch2.BBFetchException, e:
ERROR:      0016:        raise bb.build.FuncFailed(e)
ERROR:      0017:
ERROR:      0018:
ERROR:  *** 0019:base_do_unpack(d)
ERROR:      0020:
ERROR: [From file: 'base_do_unpack', lineno: 19, function: <module>]
ERROR:      0010:    rootdir = localdata.getVar('WORKDIR', True)
ERROR:      0011:
ERROR:      0012:    try:
ERROR:      0013:        fetcher = bb.fetch2.Fetch(src_uri, localdata)
ERROR:  *** 0014:        fetcher.unpack(rootdir)
ERROR:      0015:    except bb.fetch2.BBFetchException, e:
ERROR:      0016:        raise bb.build.FuncFailed(e)
ERROR:      0017:
ERROR:      0018:
ERROR: [From file: 'base_do_unpack', lineno: 14, function: base_do_unpack]
ERROR: Function failed: base_do_unpack
ERROR: Logfile of failure stored in: /local/cache-build-32bit/poky/build_p1022ds_release_master/tmp/work-shared/gcc-4.7.2+fsl-r19/temp/log.do_unpack.13886
[...snip...]
ERROR: Command Error: exit status: 1  Output:
Applying patch optional_libstdc.patch
patching file gcc/cp/g++spec.c
can't find file to patch at input line 30 Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: gcc-4_7-branch/gcc/doc/invoke.texi
|===================================================================
|--- gcc-4_7-branch.orig/gcc/doc/invoke.texi	2012-04-10 10:37:09.343387385 -0700
|+++ gcc-4_7-branch/gcc/doc/invoke.texi	2012-04-10 10:37:49.483389340 -0700
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
can't find file to patch at input line 64 Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: gcc-4_7-branch/gcc/c-family/c.opt
|===================================================================
|--- gcc-4_7-branch.orig/gcc/c-family/c.opt	2012-04-10 10:17:24.667330076 -0700
|+++ gcc-4_7-branch/gcc/c-family/c.opt	2012-04-10 10:37:49.483389340 -0700
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file gcc/gcc.c
Hunk #1 succeeded at 679 (offset -2 lines).
Patch optional_libstdc.patch does not apply (enforce with -f)
ERROR: Function failed: patch_do_patch

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>